spring.application.name=api
server.port=7085
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=admin
spring.datasource.password=MWZADCKIYEINQLXH

spring.flyway.enabled=true
spring.flyway.url='jdbc:postgresql://localhost:5432/orders'
spring.flyway.password=MWZADCKIYEINQLXH
spring.flyway.user=admin
spring.flyway.baselineOnMigrate=true
